name: Keep Vanta Inventory Awake
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Ping login page
        run: |
          set -e
          for i in 1 2 3; do
            curl -I --silent --show-error --fail \
              https://vanta-inventory.onrender.com/login \
              && echo "Ping $i OK" && break || (echo "Ping $i failed" && sleep 10)
          done

